config/routes.rb
Gdoc::Application.routes.draw do

  match "favourites/" => "favourites#create", :as => :add_favourite , :via => :get
  match "favourites/" => "favourites#destroy", :as => :remove_favourite,  :via => :delete

localized do

  devise_for :users
  
  root :to => 'Cycles#index'
  
  resources :participants

  resources :documents

  resources :people

  resources :photos

  resources :videos

  resources :audios

  resources :cycles

  resources :events

end

Gdoc::Application.routes.translate_from_file("config/locales/routes.yml")

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible  :address, :city, :country, :postcode
  belongs_to :addressable, :polymorphic => true 

end

app/models/audio.rb
class Audio < ActiveRecord::Base
  attr_accessible :participant_attributes, :date, :description, :duration, :format, :language, :license, :participant_id, :title, :tag_list
  has_and_belongs_to_many :events
  has_many :participates, :as => :participable  
  has_many :participants, :through => :participates
  acts_as_taggable
  has_many :favourites, :as => :favouritable, :dependent => :destroy

end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  attr_accessible :description, :end_date, :start_date, :title, :tag_list
  has_and_belongs_to_many :events 
  has_many :cycles, :as => :addressable
  validates_presence_of :title
  acts_as_taggable
  has_many :favourites, :as => :favouritable, :dependent => :destroy


end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :participant_attributes, :date, :description, :format, :language, :license, :participant_id, :title, :tag_list
  has_and_belongs_to_many :events
  has_many :participates, :as => :participable 
  has_many :participants, :through => :participates
  acts_as_taggable
  has_many :favourites, :as => :favouritable, :dependent => :destroy

end

app/models/event.rb
class Event < ActiveRecord::Base

  attr_accessible :cycle_ids, :date, :description, :participant_id, :time, :title, :tag_list
  validates_presence_of :title
  has_and_belongs_to_many :cycles
  has_and_belongs_to_many :videos
  has_and_belongs_to_many :audios
  has_and_belongs_to_many :photos
  has_and_belongs_to_many :documents
  has_many :addresses, :as => :addressable
  has_many :participates, :as => :participable  
  has_many :participants, :through => :participates

  acts_as_taggable
  has_many :favourites, :as => :favouritable, :dependent => :destroy

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  attr_accessible :favouritable_type, :favouritable_id
  belongs_to :favouritable, :polymorphic => true
  belongs_to :user 
  validates_presence_of :user, :favouritable_type, :favouritable_id
  
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :bio, :creator, :name, :image, :tag_list
  has_many :participables
  mount_uploader :image, ImageUploader

  acts_as_taggable  

  has_many :favourites, :as => :favouritable, :dependent => :destroy


end

app/models/participate.rb
class Participate < ActiveRecord::Base
  
  belongs_to :participant
  belongs_to :participable , :polymorphic => true
  
  end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :image, :date, :description, :format, :license,  :title, :tag_list

  validates_presence_of :title

  has_and_belongs_to_many :events
  has_many :participates, :as => :participable  
  has_many :participants, :through => :participates
  has_many :favourites, :as => :favouritable, :dependent => :destroy

  mount_uploader :image, ImageUploader
  acts_as_taggable

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  acts_as_tagger

  
  has_many :favourites, :dependent => :destroy
  default_scope  :include => [ :favourites]

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible  :date, :description, :duration, :format, :language, :license, :participant_id, :title, :tag_list
  has_and_belongs_to_many :events 
  has_many :participates, :as => :participable  
  has_many :participants, :through => :participates
  acts_as_taggable
  validates_presence_of :title
  has_many :favourites, :as => :favouritable, :dependent => :destroy

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    if params[:tag]
      @events = Event.tagged_with(params[:tag])
    else
      @events = Event.all

   end



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @cycles = Cycle.all
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index

#    @user_tags = current_user.owned_tags

    @photos = current_user.collections.find(params[:photo_id])    
    @item = @photos.items.find(params[:id])
    @user_items = current_user.find_all(params[:tag]).photos
#    @user_photos_tagged = current_user.tag(@some_photo, :with => params[:tag], :on => :photos)


  end


  def show
#    @tag = Participant.tagged_with(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favourite_helper.rb
module FavouriteHelper
  
  def favourite_button(var)
    
    favourited= current_user.favourites.where(:favouritable_id => var.id, :favouritable_type => var.class)
    
    if favourited.present?

      render("favourites/delete_favourite", :t => var) if current_user.favourites.where(:favouritable_id => var.id, :favouritable_type => var.class).present?
      #("favourites/favourite", :t => var)
    else
      render("favourites/favourite", :t => var)
    end
    
  end
  
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/events/_form.html.erb
<div  id="single-asset" class="span7 ofsset1">

  <%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
       <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>  
    <div class="field">
      <%= f.label t("metadata.title") %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">  
      <%= f.label t("metadata.start_date") %><br />
      <%= f.datepicker :date, :dateFormat => "yy-mm-dd" %>
    </div>
    <div class="field">
      <%= f.label t("metadata.time") %><br />
       <%= f.text_field :time , :class => "time-picker" %>
    </div>
    <div class="field">
      <%= f.label t("metadata.description") %><br />
      <%= f.text_area :description %>
    </div>
    
  <div class="field">
     <% if !@cycles.nil? %>  
       <%= f.label :cycle_ids %><br />
       <%= f.select(:cycle_ids, @cycles.collect {|c| [c.title, c.id]}) %>
     <% end %>
  </div>

  <div class="field" style="background-color: #E89BB6">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/events/edit.html.erb
<h1><%= t("title.edit_event") %></h1>

<%= render 'form' %>

<%= link_to t("link.edit"), @event %> |
<%= link_to t("link.back"), events_path %>

app/views/events/index.html.erb
<h1><%= t("listing.events") %></h1>
<%= link_to t("title.new_event"), new_event_path if current_user.present?%>


<% @events.each do |t|%>

  <div class="box_container full-width span7">
    <div class="favourites">
      <%#= link_to "add to favourites",add_favourite_path(t.class,t.id), :remote => true %>
      <%#= favourite_button(t) if current_user.present? %>
    </div>
    <div class="name">
      <%= link_to t.title,event_url(t.id) %>
    </div>   
    <div class="description">
      <%= t.description  %>
    </div>
    <div class="start-end-date">
      <%= t.date %><%= t.time %>
    </div>
    <div>
     <% if t.cycles.nil? %>  
    <td><%= link_to t.cycle.title, t.cycle %></td>
    <% end %>
  </div>
   <div style="background-color: #E89BB6">
    <%= t.tag_list {|t| t} %>
   </div>


  </div>
<% end %>



<br />

app/views/events/new.html.erb
<h1><%= t("title.new_event") %></h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>


<div  id="single-asset" class="span7 ofsset1">
  <p id="notice"><%= notice %></p>
  <p>
    <h1><%= t("form.title") %>:</h1>
    <%= @event.title %>
  </p>
  
  <%= favourite_button(@event) if current_user.present? %>
  
  <p>
    <b><%=  t("form.start_date") %></b>
    <%= @event.date %>
  </p>
  
  <p>
    <b>Time:</b>
    <%= @event.time.strftime('%H:%M') if !@event.time.nil? %>
  </p>
  
  <p>
    <b><%=  t("form.description") %>:</b>
    <%= @event.description %>
  </p>
<p>
  <b>Tags:</b>
  <div style="background-color: #E89BB6">
      <%= @event.tag_list {|t| t} %>
  </div>
</p>

  <p>
   <b>Cycle:</b>
     <% if @event.cycles.present? %>  
       <%  @event.cycles.each do |c|  %>
          <td><%= link_to c.title, c.title %></td>
       <% end %>
    <% end %>
  </p>
  
  <%= link_to t("link.edit"), edit_event_path(@event) %> |
  <%= link_to t("link.back"), events_path %>
  
</div>